import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Sparkles, CheckCircle2, Box, ListOrdered, Palette, Eye, ShoppingBag, ExternalLink, Loader2, Image as ImageIcon } from 'lucide-react';
import { ProductSuggestion } from '../types';

interface AnalysisDisplayProps {
  analysis: string;
  products: ProductSuggestion[];
  onVisualize: () => Promise<void>;
  visualizationImage: string | null;
  isVisualizing: boolean;
}

export const AnalysisDisplay: React.FC<AnalysisDisplayProps> = ({ 
  analysis, 
  products,
  onVisualize,
  visualizationImage,
  isVisualizing
}) => {
  
  const generateAmazonLink = (term: string) => {
    return `https://www.amazon.com/s?k=${encodeURIComponent(term)}&tag=zenspace-20`;
  };

  return (
    <div className="space-y-8">
      {/* Main Analysis Card */}
      <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 md:p-8">
          <div className="flex items-center gap-2 mb-6 border-b border-slate-100 pb-4">
              <Sparkles className="w-6 h-6 text-emerald-500" />
              <h2 className="text-2xl font-bold text-slate-800 m-0">Your Organization Plan</h2>
          </div>
          
          <div className="prose prose-emerald max-w-none prose-headings:font-serif prose-headings:text-emerald-900 prose-p:text-slate-600 prose-li:text-slate-600">
            <ReactMarkdown
                components={{
                    h1: ({node, ...props}) => <h3 className="text-xl font-bold mt-6 mb-3 text-emerald-800 flex items-center gap-2" {...props} />,
                    h2: ({node, ...props}) => <h3 className="text-xl font-bold mt-8 mb-4 text-emerald-800 flex items-center gap-2 border-b border-emerald-100 pb-2" {...props} />,
                    ul: ({node, ...props}) => <ul className="list-disc pl-5 space-y-2 my-4" {...props} />,
                    ol: ({node, ...props}) => <ol className="list-decimal pl-5 space-y-3 my-4" {...props} />,
                    li: ({node, ...props}) => <li className="text-slate-700 leading-relaxed" {...props} />,
                    strong: ({node, ...props}) => <span className="font-semibold text-emerald-700" {...props} />,
                    p: ({node, ...props}) => <p className="mb-4 text-slate-600 leading-relaxed" {...props} />,
                }}
            >
                {analysis}
            </ReactMarkdown>
          </div>
      </div>

      {/* Visualization Section */}
      <div className="bg-zinc-900 rounded-2xl shadow-lg overflow-hidden text-white">
        <div className="p-6 border-b border-zinc-800 flex items-center justify-between">
            <div className="flex items-center gap-3">
                <Eye className="w-6 h-6 text-purple-400" />
                <div>
                  <h3 className="text-lg font-bold text-white">Visualize Your Potential</h3>
                  <p className="text-xs text-zinc-400">AI-generated preview of your organized space</p>
                </div>
            </div>
        </div>

        <div className="p-6">
          {visualizationImage ? (
            <div className="relative rounded-xl overflow-hidden border border-zinc-700 group">
               <img 
                  src={`data:image/png;base64,${visualizationImage}`} 
                  alt="AI Generated Organized Room" 
                  className="w-full h-auto object-cover"
               />
               <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-4">
                  <span className="text-xs font-mono text-purple-300 uppercase tracking-widest">Generated by Nano Banana</span>
               </div>
            </div>
          ) : (
            <div className="bg-zinc-800/50 rounded-xl p-8 text-center border border-zinc-700 border-dashed">
               {isVisualizing ? (
                 <div className="flex flex-col items-center py-8">
                    <Loader2 className="w-10 h-10 text-purple-500 animate-spin mb-4" />
                    <p className="text-zinc-300 font-medium">Dreaming up your new room...</p>
                    <p className="text-zinc-500 text-sm mt-2">Applying organization rules & lighting adjustments</p>
                 </div>
               ) : (
                 <div className="flex flex-col items-center py-4">
                    <ImageIcon className="w-12 h-12 text-zinc-600 mb-4" />
                    <p className="text-zinc-300 mb-6 max-w-md mx-auto">
                      Want to see what this room could look like after following the plan? 
                      Tap the button below to generate a realistic preview.
                    </p>
                    <button 
                      onClick={onVisualize}
                      className="group relative px-6 py-3 rounded-full bg-purple-600 hover:bg-purple-500 text-white font-semibold transition-all shadow-[0_0_20px_-5px_rgba(147,51,234,0.5)] hover:shadow-[0_0_25px_-5px_rgba(147,51,234,0.7)] flex items-center gap-2"
                    >
                      <Sparkles className="w-4 h-4 group-hover:animate-spin-slow" />
                      Generate Visualization
                    </button>
                 </div>
               )}
            </div>
          )}
        </div>
      </div>

      {/* Product Recommendations */}
      {products.length > 0 && (
        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 md:p-8">
           <div className="flex items-center gap-2 mb-6">
              <ShoppingBag className="w-6 h-6 text-orange-500" />
              <h2 className="text-2xl font-bold text-slate-800 m-0">Shop the Look</h2>
           </div>
           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {products.map((product, idx) => (
                <a 
                  key={idx}
                  href={generateAmazonLink(product.searchTerm)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex flex-col justify-between p-5 rounded-xl border border-slate-200 hover:border-orange-200 hover:shadow-md transition-all group bg-slate-50/50 hover:bg-white"
                >
                  <div>
                    <div className="flex justify-between items-start mb-2">
                      <h4 className="font-bold text-slate-800 group-hover:text-orange-600 transition-colors">{product.name}</h4>
                      <ExternalLink className="w-4 h-4 text-slate-400 group-hover:text-orange-500" />
                    </div>
                    <p className="text-sm text-slate-600 mb-4">{product.reason}</p>
                  </div>
                  <div className="mt-auto pt-3 border-t border-slate-200/60 flex items-center text-xs font-bold text-orange-600 uppercase tracking-wider">
                    Find on Amazon &rarr;
                  </div>
                </a>
              ))}
           </div>
           <div className="mt-4 text-center">
              <p className="text-xs text-slate-400 italic">
                *As an Amazon Associate we earn from qualifying purchases.
              </p>
           </div>
        </div>
      )}
    </div>
  );
};